# Generated by Django 4.2.20 on 2025-12-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_inquiries', models.IntegerField(default=0)),
                ('new_inquiries', models.IntegerField(default=0)),
                ('inquiries_by_country', models.JSONField(default=dict)),
                ('inquiries_by_service', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Inquiry Statistics',
            },
        ),
    ]
